spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nextsteps
    username: nextsteps
    password: nextsteps
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
